# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract numeric data from genotype field of VCF
#' 
#' @param x A dataframe
#' @param element A string matching the element to be retrieved
#' @export
extractGT2NM <- function(x, element = "DP") {
    .Call('vcfR_extractGT2NM', PACKAGE = 'vcfR', x, element)
}

one <- function() {
    .Call('vcfR_one', PACKAGE = 'vcfR')
}

#' Extract numeric data from genotype field of VCF
#' 
#' @param x A NumericMatrix
#' @param maxbp max
#' @param winsize
#' @export
NM2winNM <- function(x, pos, maxbp, winsize = 100L) {
    .Call('vcfR_NM2winNM', PACKAGE = 'vcfR', x, pos, maxbp, winsize)
}

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('vcfR_timesTwo', PACKAGE = 'vcfR', x)
}

