# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract numeric data from genotype field of VCF
#' 
#' @param x A dataframe.
#' @export
extractGT2NM <- function(x) {
    .Call('vcfR_extractGT2NM', PACKAGE = 'vcfR', x)
}

one <- function() {
    .Call('vcfR_one', PACKAGE = 'vcfR')
}

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('vcfR_timesTwo', PACKAGE = 'vcfR', x)
}

